name: kenya_administrative_divisions
description: The Kenya Administrative Divisions is a package that provides functionality to retrieve administrative divisions data about Kenya. It includes information about counties, constituencies, and wards..
version: 1.0.2

repository: https://github.com/michaelnjuguna/kenya-administrative-divisions-dart

environment:
  sdk: ">=3.0.0 <4.0.0"

# Add regular dependencies here.

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0

assets:
  - lib/src/county.json
dependencies:
  path: ^1.9.1
  resource_portable: ^3.1.0
